---

- name: "configuration play." 
  hosts: web
  remote_user: ubuntu
  become: true
  become_method: sudo
  become_user: root  
  gather_facts: false
  vars:
    - ansible_python_interpreter: /usr/bin/python3
    - ansible_host_key_checking: false
    - ansible_stdout_callback: yaml

  pre_tasks:
    - name: "wait 600 seconds for target connection to become reachable/usable."
      wait_for_connection:
        connect_timeout: 10
        delay: 3
        sleep: 2
        timeout: 600

    - name: "install python for Ansible."
      apt:
        name: python3
        state: present
        update_cache: yes # update cache before installing
        autoremove: yes # remove unused packages after installation

  roles:
    - configure-server
    - configure-prometheus-node-exporter
