---
- name: "Add nodejs 13.x from nodesource."
  become: true
  shell: |
    curl -fsSL https://deb.nodesource.com/setup_lts.x | sudo -E bash -
    sudo apt install nodejs -y

- name: "install n (node version manager)."
  become: true
  npm:
    name: n
    global: yes
    production: yes

- name: "install nodejs 13.8.0"
  become: true
  shell: n 13.8.0

- name: "install pm2 globally"
  become: true
  npm:
    name: pm2
    global: yes
    production: yes
    state: present
