---
- name: "Add nodejs 13.x from nodesource."
  become: true
  shell: |
    curl -fsSL https://deb.nodesource.com/setup_13.x | sudo -E bash -

- name: "install nodejs 13."
  become: true
  apt:
    name: ["nodejs"]
    state: latest

- name: "install pm2 globally"
  become: true
  npm:
    name: pm2
    global: yes
    production: yes
    state: present
